version: "3.9"

services:
  mysql:
    image: mysql
    container_name: "profile_project_mysql"
    restart: always
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_DATABASE=profile_project
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=123456_ultra_secure_password
      - MYSQL_PORT=3306
    ports:
      - "3306:3306"
    expose:
      - "3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - profile_project
    volumes:
      - ./data/db:/var/lib/mysql
  web:
    container_name: "profile_project_django"
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - profile_project

networks:
  profile_project:
